//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/Defaultlnput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Defaultlnput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Defaultlnput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Defaultlnput"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""884fb40b-1afe-4210-8f4e-33fac5610d8c"",
            ""actions"": [
                {
                    ""name"": ""ResetView"",
                    ""type"": ""Button"",
                    ""id"": ""70e1fe09-b117-4315-8a88-1e510c6a11ff"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartNewRound"",
                    ""type"": ""Button"",
                    ""id"": ""8e1f27d0-f85f-4ccd-a509-371577f5a279"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""70e52890-d575-4fdc-bcf4-ce169c6da148"",
                    ""path"": ""<XRController>/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""365863c0-06b3-422a-a18e-c2c392bf46fd"",
                    ""path"": ""<XRController>/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartNewRound"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_ResetView = m_Default.FindAction("ResetView", throwIfNotFound: true);
        m_Default_StartNewRound = m_Default.FindAction("StartNewRound", throwIfNotFound: true);
    }

    ~@Defaultlnput()
    {
        UnityEngine.Debug.Assert(!m_Default.enabled, "This will cause a leak and performance issues, Defaultlnput.Default.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_ResetView;
    private readonly InputAction m_Default_StartNewRound;
    public struct DefaultActions
    {
        private @Defaultlnput m_Wrapper;
        public DefaultActions(@Defaultlnput wrapper) { m_Wrapper = wrapper; }
        public InputAction @ResetView => m_Wrapper.m_Default_ResetView;
        public InputAction @StartNewRound => m_Wrapper.m_Default_StartNewRound;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @ResetView.started += instance.OnResetView;
            @ResetView.performed += instance.OnResetView;
            @ResetView.canceled += instance.OnResetView;
            @StartNewRound.started += instance.OnStartNewRound;
            @StartNewRound.performed += instance.OnStartNewRound;
            @StartNewRound.canceled += instance.OnStartNewRound;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @ResetView.started -= instance.OnResetView;
            @ResetView.performed -= instance.OnResetView;
            @ResetView.canceled -= instance.OnResetView;
            @StartNewRound.started -= instance.OnStartNewRound;
            @StartNewRound.performed -= instance.OnStartNewRound;
            @StartNewRound.canceled -= instance.OnStartNewRound;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnResetView(InputAction.CallbackContext context);
        void OnStartNewRound(InputAction.CallbackContext context);
    }
}
